### ISSUE TITLE
¿Como sabemos cuando un usuario puede estudiar?

### ISSUE THREAD

**Issue by fjromeero** [JoseCarlosJC/UseTime#10]
Abro este issue para discutir sobre como podemos interpretar el concepto de rutina (he decidido nombrarlo así, aunque si prefieres nombrarlo de diferente forma me dices) refiríendome a aquellas franjas horarias de un determinado día de la semana que el usuario sabe que no podrá estudiar independientemente de la semana que sea.
En mi caso se me ha ocurrido implementarlas de dos formas distintas:
- 1. Almacenar la fecha de inicio como un tipo Date, que almacene el día en el calendario y luego para comprobar en la asignación de tareas si está ocupada tendríamos que sumarle múltiplos de 7 hasta llegar a dicha fecha como se explica aquí (https://unipython.com/sumar-y-restar-dias-a-una-fecha-en-java-script/)  la cual no recomiendo.
- 2. Y la otra opción que se me ha ocurrido es representarlas de la siguiente forma: una variable que contenga el día de la semana y otra que sea un array de tuplas de tipo Date que representarán las distintas franjas horarias que estarán ocupadas. Y luego para comprobar si una tarea se puede asignar a una franja horaria determinada puedes obtener el dia de la semana de la fecha como explica aquí: https://parzibyte.me/blog/2020/03/09/javascript-dia-semana-segun-fecha/amp/

Si te parece bien alguna de estas dos me dices, y si no para intentar buscar otra forma. @JoseCarlosJC

**Comment by JoseCarlosJC** [comment]
Buenas @fjromeero . El uso de rutinas que especifiquen cuándo no puede un usuario estudiar no lo veo viable. Pienso que sería más conveniente saber cuando sí puede estudiar.

**Comment by fjromeero** [comment]
> Buenas @fjromeero . El uso de rutinas que especifiquen cuándo no puede un usuario estudiar no lo veo viable. Pienso que sería más conveniente saber cuando sí puede estudiar.

De acuerdo y ¿Cómo sé sabe cuando si puede estudiar? @JoseCarlosJC

**Comment by JoseCarlosJC** [comment]
El usuario indicará cuándo puede estudiar @fjromeero . Especificará para cada día de la semana (lunes, martes,...,domingo) de qué hora a qué hora puede estudiar. Por ejemplo:
* Lunes: de 16:00 a 20:00
* Martes: de 16:00 a 18:00 y de 20:00 a 22:00
* Miércoles: no estudia
* Jueves: de 10:30 a 13:00
* ...

**Comment by JoseCarlosJC** [comment]
Además para un día en concreto, como el 14-10-2022 (que sería un lunes) el usuario puede especificar un horario de estudio distinto al establecido por normal general antes. Es decir, puede indicar que ese día estudiará de 17:00 a 19:00, o no estudiará, etc.

**Comment by JoseCarlosJC** [comment]
En ambos casos, para un día se especifica cuándo se puede estudiar. Cambia la forma de indicar el día: puede ser lunes, jueves..., o uno concreto como 14-10-2022
