### ISSUE TITLE
¿Cuándo puede comenzar un tramo horario y cuanta puede ser su duraci'on?

### ISSUE THREAD

**Issue by fjromeero** [JoseCarlosJC/UseTime#14]
Respecto a #13 de que manera podemos representar los tramos horarios para que se puedan aceptar tanto huecos libres entre tareas rutinarias que se vayan repitiendo todas las semanas a lo largo del tiempo, o entre eventos esporádicos y puntuales

**Comment by JJ** [comment]
Esto está más o menos planteado como un problema, pero *realmente* no plantea el verdadero problema. ¿Pueden empezar las tareas en cualquier momento de una hora? ¿Sólo a las horas en punto? ¿A los 5 minutos?

**Comment by fjromeero** [comment]
Para solucionar #13 es necesario realizar un modelo con el que podamos representar un tramo horario, que pueda empezar a cualquiera hora, y que además podamos usarlo tanto para tareas rutinarias que se repitan a lo largo de las semanas , como para eventos puntuales

**Comment by JJ** [comment]
Poner "problema con" o "problema de" no lo hace un problema. Se trata simplemente de que enunciéis el contexto, qué es lo que se tiene que usar en la lógica de negocio y qué implica todo eso.

**Comment by fjromeero** [comment]
> Poner "problema con" o "problema de" no lo hace un problema. Se trata simplemente de que enunciéis el contexto, qué es lo que se tiene que usar en la lógica de negocio y qué implica todo eso.

Lo entiendo, pero no se como expresar de forma escueta en el titulo todo lo que plantea este problema

**Comment by fjromeero** [comment]
Referente a : #13 de que manera se puede representar un tramo horario, que pueda empezar y terminar a cualquiera hora y minuto.

**Comment by fjromeero** [comment]
> Si no lo sabes expresar, es complicado que lo soluciones. El primer paso para solucionar un problema es entender en qué consiste.

Creo que ya representa un problema
