### ISSUE TITLE
¿Cómo puedo representar el horario de un usuario?

### ISSUE THREAD

**Issue by fjromeero** [JoseCarlosJC/UseTime#15]
Referente a #3 
Hay que representar el horario de un usuario, tanto los huecos libres y ocupados.

**Comment by JJ** [comment]
Esto ni siquiera intenta presentarse como un problema. Por favor, tratad de seguir la metodología correcta. De esta forma es imposible que se cree valor para el cliente.

**Comment by fjromeero** [comment]
Hay que representar el horario de un usuario, es decir los huecos libres y ocupados.
