### ISSUE TITLE
Elección lenguaje de programación

### ISSUE THREAD

**Issue by fjromeero** [JoseCarlosJC/UseTime#7]
Hola @JoseCarlosJC , ya se te aprobó el PR del objetivo 1, asi que puedes mergear ya.
Abro este issue para comentar la elección del lenguaje de programación y así poder comenzar a desarrollar el Objetivo 2 abriendo un PR, ¿Tienes ya una idea de que lenguaje quieres usar?

**Comment by JoseCarlosJC** [comment]
¡Hola @fjromeero! El proyecto se va a desarrollar en **TypeScript**.
